Repository domits1/Domits, pull requests merged in 2025-02, with the labels that each got.

#1563 #1552 + #1553 Updates gradle versions to 8.1. Removes @react-native-community/blur and updates duplicate react-native-voice package
  app/Domits/android/app/build.gradle
  app/Domits/android/build.gradle
  app/Domits/package.json
Labels: Bug

#1566 Fix .env/api key ci pipeline error and changes directory path to Onbo…
  app/Domits/src/header/GooglePlacesInput.js
  app/Domits/src/navigation/appNavigation.js
Labels: Bug, Cleanup

#1565 New interns photo's to about page (leave open till ~ feb 11 2025)
  web/src/images/about-img/Ryan-compressed.png
  web/src/pages/about/About.js
Labels: DevOps

#1578 App/Web | Add .env functionality
  app/Domits/.env.example
  app/Domits/babel.config.js
  app/Domits/package.json
  app/Domits/src/navigation/appNavigation.js
  app/Domits/src/screens/detailpage.js
  web/.env.example
  web/package.json
  web/src/dotenv.js
Labels: Security, Dependencies, Refactoring

#1579 adds Santosh' photo to about page
  web/src/images/about-img/Santosh.png
  web/src/pages/about/About.js
Labels: DevOps

#1589 App | Preparation google play store release | UX Cleanup + Navigation Refactor
  app/Domits/App.js
  app/Domits/src/header/header.js
  app/Domits/src/navigation/accountNavigationStack.js
  app/Domits/src/navigation/appNavigation.js
  app/Domits/src/navigation/mainNavigationStack.js
  app/Domits/src/navigation/messagesStackNavigator.js
  app/Domits/src/screens/account.js
  app/Domits/src/screens/detailpage.js
  app/Domits/src/screens/homeScreen.js
  app/Domits/src/screens/login/confirmMail.js
  app/Domits/src/screens/login/loginScreen.js
Labels: Cleanup, Refactoring, Technical debt

#1590 App | Android App Release #45 | UX Cleanup + seperating delete account function for reusability.
  app/Domits/android/app/build.gradle
  app/Domits/android/gradle.properties
  app/Domits/src/features/auth/DeleteAccount.js
  app/Domits/src/header/header.js
  app/Domits/src/screens/account.js
  app/Domits/src/screens/homeScreen.js
Labels: Security, Cleanup, Refactoring, Technical debt

#1603 App homescreen refactor
  app/Domits/src/components/utils/mappings/FormatAccommodationData.js
  app/Domits/src/features/search/FetchAccommodation.js
  app/Domits/src/features/search/FetchAccommodationsData.js
  app/Domits/src/features/search/FetchOwnerData.js
  app/Domits/src/header/header.js
  app/Domits/src/images/icons/app-bookings-icon-black.png
  app/Domits/src/navigation/mainNavigationStack.js
  app/Domits/src/screens/Acommodations.js
  app/Domits/src/screens/detailpage.js
  app/Domits/src/screens/listingDetailScreen/components/.gitkeep
  app/Domits/src/screens/listingDetailScreen/context/.gitkeep
  app/Domits/src/screens/listingDetailScreen/hooks/.gitkeep
  app/Domits/src/screens/listingDetailScreen/listingDetailScreen.js
  app/Domits/src/screens/listingDetailScreen/navigation/.gitkeep
  app/Domits/src/screens/listingDetailScreen/pages/.gitkeep
  app/Domits/src/screens/listingDetailScreen/services/.gitkeep
  app/Domits/src/screens/listingDetailScreen/store/.gitkeep
  app/Domits/src/screens/listingDetailScreen/styles/listingDetailStyles.js
  app/Domits/src/screens/listingDetailScreen/tests/.gitkeep
  app/Domits/src/screens/listingDetailScreen/utils/.gitkeep
  app/Domits/src/screens/listingDetailScreen/views/AmenitiesPopup.js
  app/Domits/src/ui-components/FeatureIcons.js
Labels: Documentation, Cleanup, Technical debt

#1613 App | Implement Authorization Method
  app/Domits/index.js
  app/Domits/src/amplifyconfiguration.json
  app/Domits/src/features/auth/LogoutAccount.js
  app/Domits/src/features/auth/RetrieveAccessToken.js
  app/Domits/src/features/hostdashboard/hostproperty/components/.gitkeep
  app/Domits/src/features/hostdashboard/hostproperty/context/.gitkeep
  app/Domits/src/features/hostdashboard/hostproperty/hooks/.gitkeep
  app/Domits/src/features/hostdashboard/hostproperty/navigation/.gitkeep
  app/Domits/src/features/hostdashboard/hostproperty/pages/.gitkeep
  app/Domits/src/features/hostdashboard/hostproperty/services/.gitkeep
  app/Domits/src/features/hostdashboard/hostproperty/services/DeleteProperty.js
  app/Domits/src/features/hostdashboard/hostproperty/store/.gitkeep
  app/Domits/src/features/hostdashboard/hostproperty/styles/.gitkeep
  app/Domits/src/features/hostdashboard/hostproperty/tests/.gitkeep
  app/Domits/src/features/hostdashboard/hostproperty/utils/.gitkeep
  app/Domits/src/features/hostdashboard/hostproperty/views/.gitkeep
  app/Domits/src/screens/account.js
  web/src/tests/cypress/screenshots/Hostdashboard.cy.js/Landing Page and HostDashboard Tests -- should load and display user information (failed).png
  web/src/tests/cypress/screenshots/Hostdashboard.cy.js/Landing Page and HostDashboard Tests -- should navigate to the Add accommodation page when clicking the button (failed).png
Labels: Security, Cleanup, Refactoring, Technical debt
