Repository domits1/Domits, pull requests merged in 2025-05, with the labels that each got.

#1891 Guest wishlist
  web/.gitignore
  web/package-lock.json
  web/package.json
  web/src/App.js
  web/src/features/guestdashboard/Pages.js
  web/src/features/guestdashboard/components/GuestActions.js
  web/src/features/guestdashboard/components/GuestSelector.js
  web/src/features/guestdashboard/pages/GuestWishlistPage.js
  web/src/features/guestdashboard/styles/GuestActions.scss
  web/src/features/guestdashboard/styles/GuestSelector.scss
  web/src/features/guestdashboard/styles/GuestWishlistPage.scss
  web/src/features/guestdashboard/utils/authUtils.js
  web/src/images/4-Bed-Kona-Homes.jpeg
  web/src/images/Greece-Yacht.jpeg
  web/src/images/cabin-in-the-winter-at.jpg
  web/src/images/villas-for-sale-spain.jpg
  web/src/index.js
  web/src/pages/home/AccommodationCard.js
  web/src/ui-components/index.js
Labels: Guest feature/request

#1918 Updated the api url endpoint
  web/src/components/base/SearchBar.jsx
  web/src/pages/home/Accommodations.js
Labels: Refactoring

#1909 App: combining host and guest account screen
  app/Domits/src/features/hostdashboard/hostcalendar/screens/HostCalendarTab.js
  app/Domits/src/features/hostdashboard/hostfinance/screens/HostPaymentsTab.js
  app/Domits/src/features/hostdashboard/hostproperty/screens/HostListingsTab.js
  app/Domits/src/features/hostdashboard/screens/HostDashboardTab.js
  app/Domits/src/header/bookings.js
  app/Domits/src/navigation/accountNavigationStack.js
  app/Domits/src/navigation/mainNavigationStack.js
  app/Domits/src/navigation/utils/NavigationNameConstants.js
  app/Domits/src/screens/Landing.js
  app/Domits/src/screens/account.js
  app/Domits/src/screens/accounthome/components/TabHeader.js
  app/Domits/src/screens/accounthome/components/TabItem.js
  app/Domits/src/screens/accounthome/features/accountdashboard/screens/AccountDashboardTab.js
  app/Domits/src/screens/accounthome/features/accountdashboard/styles/AccountDashboardStyles.js
  app/Domits/src/screens/accounthome/features/appsettings/screens/AppSettingsTab.js
  app/Domits/src/screens/accounthome/features/appsettings/styles/AppSettingsStyles.js
  app/Domits/src/screens/accounthome/features/feedback/screens/FeedbackTab.js
  app/Domits/src/screens/accounthome/guestaccounthome/screens/GuestHome.js
  app/Domits/src/screens/accounthome/hostaccounthome/screens/HostHome.js
  app/Domits/src/screens/accounthome/screens/AccountHome.js
  app/Domits/src/screens/accounthome/styles/AccountHomeStyles.js
  app/Domits/src/screens/accounthome/views/BookingsView.js
  app/Domits/src/screens/accounthome/views/DashboardView.js
  app/Domits/src/screens/accounthome/views/FinancialsAndPricingView.js
  app/Domits/src/screens/accounthome/views/HelpAndSupportView.js
  app/Domits/src/screens/accounthome/views/HostOnboardingView.js
  app/Domits/src/screens/accounthome/views/MarketingAndMonitoringView.js
  app/Domits/src/screens/accounthome/views/PreferencesView.js
  app/Domits/src/screens/accounthome/views/PropertyManagementView.js
  app/Domits/src/screens/guestdashboard/GuestHelpAndFeedbackTab.js
  app/Domits/src/screens/guestdashboard/GuestPaymentsTab.js
  app/Domits/src/screens/guestdashboard/GuestReviewsTab.js
  app/Domits/src/screens/guestdashboard/GuestSettingsTab.js
  app/Domits/src/screens/guestdashboard/screens/GuestBookings.js
  app/Domits/src/screens/hostdashboard/features/reservations/screens/ReservationsTab.js
  app/Domits/src/screens/loadingscreen/screens/LoadingScreen.js
  app/Domits/src/screens/login/loginScreen.js
  app/Domits/src/screens/login/screens/register.js
  app/Domits/src/screens/login/styles/RegisterStyles.js
Labels: Cleanup

#1931 Frontend classnames optimalizations
  web/src/components/base/SearchBar.jsx
  web/src/styles/sass/base/SearchBar.scss
Labels: Cleanup

#1992 App: fix dependencies
  frontend/app/Domits/android/build.gradle
  frontend/app/Domits/package.json
Labels: Bug
