Repository domits1/Domits, pull requests merged in 2025-04, with the labels that each got.

#1782 Code clean up #2
  package-lock.json
  package.json
  web/src/components/base/FilterButton.jsx
  web/src/components/base/SearchBar.css
  web/src/components/base/SearchBar.jsx
  web/src/pages/home/Accommodations.js
  web/src/pages/home/FilterLogic.jsx
  web/src/pages/home/FilterUi.jsx
Labels: Cleanup

#1785 temp fix for the stripe error
  web/src/features/verification/hostverification/hooks/useStripeVerification.js
Labels: Bug

#1802 alle inline styling in de searchbar uitgehaald en in aparte css gezet (wordt scss)
  web/src/components/base/SearchBar.css
  web/src/components/base/SearchBar.jsx
Labels: Cleanup

#1797 App layout responsiveness
  app/Domits/src/components/BottomTabNavigator.js
  app/Domits/src/features/search/HomeScreen.js
  app/Domits/src/features/search/PropertiesSearchResultsScreen.js
  app/Domits/src/features/search/hooks/.gitkeep
  app/Domits/src/features/search/hooks/FetchAccommodation.js
  app/Domits/src/features/search/hooks/FetchAccommodationsData.js
  app/Domits/src/features/search/hooks/FetchOwnerData.js
  app/Domits/src/features/search/screens/.gitkeep
  app/Domits/src/features/search/styles/PropertiesSearchResultsStyles.js
  app/Domits/src/features/translation/store/en.json
  app/Domits/src/features/translation/store/nl.json
  app/Domits/src/navigation/appNavigation.js
  app/Domits/src/navigation/mainNavigationStack.js
  app/Domits/src/navigation/styles/BottomTabNavigatorStyles.js
  app/Domits/src/screens/BottomTabNavigator.js
  app/Domits/src/screens/hostdashboard/components/HostSectionView.js
  app/Domits/src/screens/hostdashboard/styles/HostSectionStyles.js
  app/Domits/src/screens/loadingscreen/screens/LoadingScreen.js
  app/Domits/src/screens/propertyDetailsScreen/components/BookingPopup.js
  app/Domits/src/screens/propertyDetailsScreen/hooks/.gitkeep
  app/Domits/src/screens/propertyDetailsScreen/hooks/RenderAmenities.js
  app/Domits/src/screens/propertyDetailsScreen/screens/propertyDetailsScreen.js
  app/Domits/src/screens/propertyDetailsScreen/styles/propertyDetailsStyles.js
  app/Domits/src/screens/propertyDetailsScreen/views/PropertyImagesView.js
  app/Domits/src/screens/propertyDetailsScreen/views/PropertyMainDetailsView.js
  app/Domits/src/screens/propertyDetailsScreen/views/SelectBookingDatesCalendarView.js
  app/Domits/src/styles/.gitkeep
  app/Domits/src/styles/COLORS.js
Labels: Refactoring

#1873 App navigation refactoring
  app/Domits/src/features/auth/DeleteAccount.js
  app/Domits/src/features/auth/LogoutAccount.js
  app/Domits/src/features/bookingengine/screens/BookingEngineScreen.js
  app/Domits/src/features/bookingengine/screens/PaymentAcceptedScreen.js
  app/Domits/src/features/bookingengine/screens/PaymentDeclinedScreen.js
  app/Domits/src/features/bookingengine/simulateStripe.js
  app/Domits/src/features/hostdashboard/hostproperty/screens/HostListingsTab.js
  app/Domits/src/features/hostdashboard/screens/HostDashboardTab.js
  app/Domits/src/features/search/PropertiesSearchResultsScreen.js
  app/Domits/src/header/header.js
  app/Domits/src/navigation/NavigationFunctions.js
  app/Domits/src/navigation/accountNavigationStack.js
  app/Domits/src/navigation/mainNavigationStack.js
  app/Domits/src/navigation/utils/NavigationNameConstants.js
  app/Domits/src/screens/account.js
  app/Domits/src/screens/accounthome/hostaccounthome/screens/HostHome.js
  app/Domits/src/screens/guestdashboard/GuestSettingsTab.js
  app/Domits/src/screens/login/loginScreen.js
  app/Domits/src/screens/oldHostonboarding/PriceProperty.js
  app/Domits/src/screens/profile/hostprofile/screens/HostSettingsTab.js
  app/Domits/src/screens/profile/utils/ProfileFunctions.js
  app/Domits/src/screens/propertyDetailsScreen/screens/propertyDetailsScreen.js
Labels: Refactoring
