Repository domits1/Domits, pull requests merged in 2025-03, with the labels that each got.

#1731 Web homepage fetch
  web/src/pages/home/AccommodationCard.js
  web/src/pages/home/homePage.js
  web/src/pages/home/services/fetchProperties.js
Labels: Refactoring, Technical debt

#1735 Updates progress indicator
  web/src/pages/home/Accommodations.js
  web/src/pages/home/homePage.js
  web/src/pages/home/services/fetchProperties.js
Labels: Refactoring

#1742 Added changes from App-booking-engine-property-details, so it can be …
  app/.gitignore
  app/Domits/src/features/bookingengine/components/BookingEngineCalendarPopup.js
  app/Domits/src/features/bookingengine/components/BookingEngineGuestsPopup.js
  app/Domits/src/features/bookingengine/hooks/FetchBookingsByProperty.js
  app/Domits/src/features/bookingengine/screens/BookingEngineScreen.js
  app/Domits/src/features/bookingengine/screens/PaymentAcceptedScreen.js
  app/Domits/src/features/bookingengine/screens/PaymentDeclinedScreen.js
  app/Domits/src/features/bookingengine/simulateStripe.js
  app/Domits/src/features/bookingengine/styles/BookingEngineStyles.js
  app/Domits/src/features/bookingengine/styles/PaymentStyles.js
  app/Domits/src/features/bookingengine/utils/CalculateNumberOfNights.js
  app/Domits/src/features/checkin/screens/.gitkeep
  app/Domits/src/features/translation/store/en.json
  app/Domits/src/features/translation/store/nl.json
  app/Domits/src/navigation/mainNavigationStack.js
  app/Domits/src/screens/bookingprocess/bookingProcess.js
  app/Domits/src/screens/bookingprocess/finalBookingOverview.js
  app/Domits/src/screens/bookingprocess/personalDetailsForm.js
  app/Domits/src/screens/guestdashboard/components/.gitkeep
  app/Domits/src/screens/guestdashboard/context/.gitkeep
  app/Domits/src/screens/guestdashboard/hooks/.gitkeep
  app/Domits/src/screens/guestdashboard/navigation/.gitkeep
  app/Domits/src/screens/guestdashboard/screens/GuestBookingsTab.js
  app/Domits/src/screens/guestdashboard/services/.gitkeep
  app/Domits/src/screens/guestdashboard/store/.gitkeep
  app/Domits/src/screens/guestdashboard/styles/GuestBookingsStyles.js
  app/Domits/src/screens/guestdashboard/tests/.gitkeep
  app/Domits/src/screens/guestdashboard/utils/.gitkeep
  app/Domits/src/screens/guestdashboard/views/.gitkeep
  app/Domits/src/screens/propertyDetailsScreen/components/AmenitiesPopup.js
  app/Domits/src/screens/propertyDetailsScreen/components/BookingPopup.js
  app/Domits/src/screens/propertyDetailsScreen/components/SelectBookingDateCalendar.js
  app/Domits/src/screens/propertyDetailsScreen/context/.gitkeep
  app/Domits/src/screens/propertyDetailsScreen/hooks/.gitkeep
  app/Domits/src/screens/propertyDetailsScreen/navigation/.gitkeep
  app/Domits/src/screens/propertyDetailsScreen/screens/propertyDetailsScreen.js
  app/Domits/src/screens/propertyDetailsScreen/services/.gitkeep
  app/Domits/src/screens/propertyDetailsScreen/store/.gitkeep
  app/Domits/src/screens/propertyDetailsScreen/styles/propertyDetailsStyles.js
  app/Domits/src/screens/propertyDetailsScreen/tests/.gitkeep
  app/Domits/src/screens/propertyDetailsScreen/utils/.gitkeep
Labels: Cleanup, Refactoring
